#!/usr/bin/env node
/**
 * Downloads Roboto (Material's typeface) as woff2 subsets and writes a
 * self-hosted @font-face CSS. Self-hosting is deliberate: the app must work
 * fully offline, and a remote font request would be both a third-party
 * dependency and a flash of unstyled text.
 *
 * Latin + latin-ext only — the app is en-IN, and a full Roboto download is
 * ~10x larger for glyphs the UI never renders.
 */
import { writeFileSync, mkdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const here = dirname(fileURLToPath(import.meta.url))
const fontDir = join(here, '..', 'public', 'fonts')
mkdirSync(fontDir, { recursive: true })

// Modern Chrome/Safari/Firefox all support woff2; ask Google for it explicitly.
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36'

const WEIGHTS = [
  { name: 'regular', weight: 400 },
  { name: 'medium', weight: 500 },
  { name: 'bold', weight: 700 },
]
const SUBSETS = ['latin', 'latin-ext']

const url = `https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap`

const res = await fetch(url, { headers: { 'User-Agent': UA } })
if (!res.ok) {
  console.error(`font fetch failed: ${res.status}`)
  process.exit(1)
}
let css = await res.text()

// Google's CSS emits one @font-face per (weight, subset) with a `/* subset */`
// comment above it. Pull out only the woff2 URLs for the subsets we want.
const blocks = css.split('@font-face').slice(1)
let out = `/* Roboto — self-hosted for offline use. Generated by scripts/fetch-fonts.mjs.
   Material Design's typeface. Latin + Latin-Extended only. */\n\n`
let count = 0

for (const b of blocks) {
  const subset = (b.match(/\/\*\s*([a-z-]+)\s*\*\//) ?? [])[1]
  // Require an explicitly recognised subset: an unlabelled block would
  // otherwise produce a file named "undefined".
  if (!subset || !SUBSETS.includes(subset)) continue
  const weight = Number((b.match(/font-weight:\s*(\d+)/) ?? [])[1] ?? 400)
  const src = (b.match(/url\((https:\/\/[^)]+\.woff2)\)/) ?? [])[1]
  if (!src) continue
  const spec = WEIGHTS.find((w) => w.weight === weight)
  if (!spec) continue
  const file = `roboto-${spec.name}-${subset}.woff2`

  const bin = await fetch(src, { headers: { 'User-Agent': UA } })
  if (!bin.ok) continue
  const bytes = Buffer.from(await bin.arrayBuffer())
  writeFileSync(join(fontDir, file), bytes)
  count++

  out += `@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: ${weight};
  font-display: swap;
  src: url('/fonts/${file}') format('woff2');
  unicode-range: ${subset === 'latin'
    ? 'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD'
    : 'U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF'};
}\n\n`
}

writeFileSync(join(fontDir, 'roboto.css'), out, 'utf8')
console.log(`wrote ${count} woff2 file(s) + roboto.css to public/fonts`)
